# Generated by Django 5.2.8 on 2025-11-22 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsacknowledgement',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_monthly_amount',
            field=models.DecimalField(decimal_places=2, default=120000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Unmarried', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='responsible_member',
            field=models.ForeignKey(blank=True, help_text='The leader responsible for collecting funds from this member', limit_choices_to={'role': 'responsible_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('responsible_member', 'Responsible Member'), ('member', 'Member')], default='member', help_text='Determines user permissions', max_length=20),
        ),
    ]
